export const GET_CARDS_REQUEST: 'GET_CARDS_REQUEST' = "GET_CARDS_REQUEST";
export const GET_CARDS_SUCCESS: 'GET_CARDS_SUCCESS' = "GET_CARDS_SUCCESS";
export const GET_CARDS_FAILED: 'GET_CARDS_FAILED' = "GET_CARDS_FAILED";
export const TOOGLE_SHOW_LIKED_CARDS: 'TOOGLE_SHOW_LIKED_CARDS' = "TOOGLE_SHOW_LIKED_CARDS";
export const TOOGLE_CARD_LIKE: 'TOOGLE_CARD_LIKE' = "TOOGLE_CARD_LIKE";
export const DELETE_CARD: 'DELETE_CARD' = "DELETE_CARD";